#!/usr/bin/env python
from setup_utils import *
import os
import re

# topcat

def uninstall():
    app = actions.getAppName("topcat_doi_plugin")
    if app: actions.undeploy(app)
    actions.unregisterDB("topcat_doi_plugin")

actions, arg, props = getActions("topcat_doi_plugin-setup.properties", ["db.driver", "db.url", "db.username", "db.password"])

prop_name = "topcat_doi_plugin.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]: 
    actions.configure(prop_name, prop_list) 
    actions.checkNoErrors()

if arg == "INSTALL":
    actions.installFile(prop_name)
           
    try:
        uninstall()

        actions.registerDB("topcat_doi_plugin", props["db.driver"], props["db.url"], props["db.username"], props["db.password"])

        files = []
        
        actions.deploy(files=files, deploymentorder=145)

    except Exception, e:
        abort(str(e))

else:  # UNINSTALL
    actions.removeFile(prop_name)

    try:
        uninstall();

    except Exception, e:
        abort(str(e))
